Fixed "AtributeError" on Django 1.2.1 final
- Fixes "AttributeError: 'tuple' object has no attribute 'creation_counter'"
? Is it the 'right' fix? Where __cmp__ is really used by dbsettings?